
local CREATION = {}
local ERR = {}

CREATION.NOT_YET_CREATED = 'X'
CREATION.FILE_PATTERN = 'P'
CREATION.HAS_BEEN_CREATED = 'C'
CREATION.IS_NOT_NOVELTY = 'N'
CREATION.UNSTABLE_SIZE = 'U'
CREATION.UNEXPECTED_SIZE = 'S'
CREATION.DISAPPEARED_UNEXPECTEDLY = 'D'

return {
    CREATION = CREATION
}